### PR TITLE
Feature/201801602 bacani

### PR DESCRIPTION
**Pull request by AndrewGarcia568**

### CODE REVIEW

**Comment by harvdelacruz-eee** [comment]
Hello! Kindly include the files produced/edited when you built the package (not just the codes obtained from the videos). Thank you!

**Comment by harvdelacruz-eee** [comment]
Commenting again in case you didn't get notified. Let us know if you need any help! Thank you :)

**Comment by AndrewGarcia568** [comment]
Sorry for the late reply. May deadline po ba for this sir?

**Comment by harvdelacruz-eee** [comment]
Apologies hehe I didn't see your reply agad. No hard deadline naman for the MEs. :)

**Pull request closed without merging**
